
title: "Colombia Unfiltered"
description: "From myth to reality. A country beyond Escobar."
author: Susana Zapata
email: susyzapata98@gmail.com

baseurl: ""
url: "https://susyzapata98.github.io/colombia-unfiltered"

theme: minima

# Activar modo oscuro
minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag
