title: "Colombia Unfiltered"
description: "From myth to reality. A country beyond Escobar."
author: Susana Zapata
email: susyzapata98@gmail.com
baseurl: "" # Déjalo así si el sitio es tipo username.github.io
url: "https://susyzapata98.github.io/colombia-unfiltered" # Reemplaza con tu URL
theme: jekyll-theme-cayman


# Opcional
plugins:
  - jekyll-feed
