title: "Colombia Unfiltered"
description: "From myth to reality. A country beyond Escobar."
author: Susana Zapata
email: susyzapata98@gmail.com
baseurl: ""
url: "https://susyzapata98.github.io/colombia-unfiltered"

# Cambiamos el tema
remote_theme: mmistakes/minimal-mistakes

# Plugins recomendados por el tema
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
