title: "Colombia Unfiltered"
description: "From myth to reality. A country beyond Escobar."
author: Susana Zapata
email: susyzapata98@gmail.com

baseurl: "" # dejar vacío
url: "https://susyzapata98.github.io/colombia-unfiltered"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single

lang: es
title_separator: "|"
timezone: America/Bogota
